# Generated by Django 4.2.5 on 2023-10-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_image_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
    ]
