# Generated by Django 4.2.5 on 2023-10-18 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pic.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pic', '0003_alter_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=pic.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
