# Generated by Django 4.2.5 on 2023-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0006_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='emotion',
            field=models.TextField(default='happy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='gender',
            field=models.TextField(default='non-bynary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='race',
            field=models.TextField(default='non'),
            preserve_default=False,
        ),
    ]
